### ISSUE TITLE
TODO October 2015

### ISSUE THREAD

**Issue by benbuckman** [benbuckman/nodejs-ebay-api#21]
Keeping track of TODOs following the [refactor](https://github.com/benbuckman/nodejs-ebay-api/pull/20) and 1.x release:

- [x] export `flatten` method
- [x] ~~Re-enable **pagination**~~ _(updated: decided to [remove](https://github.com/benbuckman/nodejs-ebay-api/commit/dfd72852458e60d2c9126690bb173a10ff974b8c) this from the module; apps should implement their own pagination logic.)_
- [ ] Review all [past issues](https://github.com/benbuckman/nodejs-ebay-api/issues) and PRs

**Comment by BDiehr** [comment]
@benbuckman Are you looking to add any contributers to the project? I am actively using this package in a project and can help you go through pull requests as well as maintain it.

**Comment by benbuckman** [comment]
@BDiehr – **thank you** and sorry for taking so long to reply. Yes, contributions would be awesome. My company is currently using this in production (hence the module's revival a few months ago). I have two concerns that we'd need to address (and I realize these somewhat contradict each other):
1. For the time being, I want to approve any changes to the released module, because the stakes of a breaking change are really high for our integration.
2. I only have limited time to review PRs/issues that don't directly affect our integration.

I am allocating several hours later this week to go through issues and PRs. Are there any PRs you think are safe to merge now?

Thanks!
